In [7]:
import torch
height = width = 16

height_gap = 2 / (height - 1)
width_gap = 2 / (width - 1)
height, width = torch.meshgrid([torch.range(-1, 1, height_gap), torch.Tensor(1)])

print(torch.range(-1, 1, height_gap))
print(height)

print(width)

lr_identity = torch.stack([width, height])


print(lr_identity.shape)

tensor([-1.0000, -0.8667, -0.7333, -0.6000, -0.4667, -0.3333, -0.2000, -0.0667,
         0.0667,  0.2000,  0.3333,  0.4667,  0.6000,  0.7333,  0.8667,  1.0000])
tensor([[-1.0000],
        [-0.8667],
        [-0.7333],
        [-0.6000],
        [-0.4667],
        [-0.3333],
        [-0.2000],
        [-0.0667],
        [ 0.0667],
        [ 0.2000],
        [ 0.3333],
        [ 0.4667],
        [ 0.6000],
        [ 0.7333],
        [ 0.8667],
        [ 1.0000]])
tensor([[-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10],
        [-2.5206e+10]])
torch.Size([2, 16, 1])


/home/lrh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  
/home/lrh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


In [27]:
a = [1,2,3,4]
def func(a):
    yield a[0], a[1], a[2], a[3]
    
for i in func(a):
    print(i)

(1, 2, 3, 4)


In [10]:
a = [1,2,3,4]
print(set(a))
def func(a):
    yield a[0]
    for i in range(len(a[1:])):
        yield a[i]
    
for i in func(a):
    print(i)

{1, 2, 3, 4}
1
1
2
3


In [8]:
a = True
b = True

a and b


import random
a = random.random()
print(a < 0.5)

b = b and random.random() < 0.5

True
